=== pancanaka/opal/opal-library/src/main/resources/config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright or Â© or Copr. SSD Research Team 2011
    (XLIM Labs, University of Limoges, France).

    Contact: ssd@xlim.fr

    This software is a Java 6 library that implements Global Platform 2.x card
    specification. OPAL is able to upload and manage Java Card applet lifecycle
    on Java Card while dealing of the authentication of the user and encryption
    of the communication between the user and the card. OPAL is also able
    to manage different implementations of the specification via a pluggable
    interface.

    This software is governed by the CeCILL-C license under French law and
    abiding by the rules of distribution of free software.  You can  use,
    modify and/ or redistribute the software under the terms of the CeCILL-C
    license as circulated by CEA, CNRS and INRIA at the following URL
    "http://www.cecill.info".

    As a counterpart to the access to the source code and  rights to copy,
    modify and redistribute granted by the license, users are provided only
    with a limited warranty  and the software's author,  the holder of the
    economic rights,  and the successive licensors  have only  limited
    liability.

    In this respect, the user's attention is drawn to the risks associated
    with loading,  using,  modifying and/or developing or reproducing the
    software by the user in light of its specific status of free software,
    that may mean  that it is complicated to manipulate,  and  that  also
    therefore means  that it is reserved for developers  and  experienced
    professionals having in-depth computer knowledge. Users are therefore
    encouraged to load and test the software's suitability as regards their
    requirements in conditions enabling the security of their systems and/or
    data to be ensured and,  more generally, to use and operate it in the
    same conditions as regards security.

    The fact that you are presently reading this means that you have had
    knowledge of the CeCILL-C license and that you accept its terms.

-->
<xsd:schema targetNamespace="http://secinfo.msi.unilim.fr/opal"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns="http://secinfo.msi.unilim.fr/opal">

    <xsd:element name="cards">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="card" minOccurs="1" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="name" type="xsd:string" minOccurs="1" maxOccurs="1"/>
                            <xsd:element name="implementation" type="xsd:string" minOccurs="1" maxOccurs="1"/>
                            <xsd:element name="description" type="xsd:string" minOccurs="0" maxOccurs="1"/>
                            <xsd:element name="atrs">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="atr" minOccurs="1" maxOccurs="unbounded" type="xsd:string"/>
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>
                            <xsd:element name="isd" type="xsd:string"/>
                            <xsd:element name="scp">
                                <xsd:simpleType>
                                    <xsd:restriction base="xsd:string">
                                        <xsd:enumeration value="01_05"/>
                                        <xsd:enumeration value="02_04"/>
                                        <xsd:enumeration value="02_05"/>
                                        <xsd:enumeration value="02_0A"/>
                                        <xsd:enumeration value="02_14"/>
                                        <xsd:enumeration value="02_15"/>
                                        <xsd:enumeration value="02_45"/>
                                        <xsd:enumeration value="02_55"/>
                                        <xsd:enumeration value="03_05"/>
                                        <xsd:enumeration value="03_0D"/>
                                        <xsd:enumeration value="03_25"/>
                                        <xsd:enumeration value="03_2D"/>
                                        <xsd:enumeration value="03_65"/>
                                        <xsd:enumeration value="03_6D"/>
                                    </xsd:restriction>
                                </xsd:simpleType>
                            </xsd:element>
                            <xsd:element name="tp">
                                <xsd:simpleType>
                                    <xsd:restriction base="xsd:string">
                                        <xsd:enumeration value="T=0"/>
                                        <xsd:enumeration value="T=1"/>
                                    </xsd:restriction>
                                </xsd:simpleType>
                            </xsd:element>
                            <xsd:element name="keys">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="key" minOccurs="1" maxOccurs="unbounded">
                                            <xsd:complexType>
                                                <xsd:sequence>
                                                    <xsd:element name="type" minOccurs="1" maxOccurs="1">
                                                        <xsd:simpleType>
                                                            <xsd:restriction base="xsd:string">
                                                                <xsd:enumeration value="DES_ECB"/>
                                                                <xsd:enumeration value="SCGemVisa2"/>
                                                                <xsd:enumeration value="DES_CBC"/>
                                                                <xsd:enumeration value="AES_CBC"/>
                                                            </xsd:restriction>
                                                        </xsd:simpleType>
                                                    </xsd:element>
                                                    <xsd:element name="version" type="xsd:unsignedByte"  minOccurs="1" maxOccurs="1"/>
                                                    <xsd:element name="id" type="xsd:unsignedByte" minOccurs="0" maxOccurs="1"/>
                                                    <xsd:element name="value" type="xsd:string"  minOccurs="1" maxOccurs="1"/>
                                                </xsd:sequence>
                                            </xsd:complexType>
                                        </xsd:element>
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

</xsd:schema>

=== pancanaka/opal/opal-library/src/test/resources/test-config.xml
<?xml version="1.0" encoding="UTF-8"?>

<opal:cards xmlns:opal="http://secinfo.msi.unilim.fr/opal"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://secinfo.msi.unilim.fr/opal config.xsd">


    <card>
        <name>CardTest02_04</name>
        <implementation>fr.xlim.ssd.opal.library.commands.GP2xCommands</implementation>
        <atrs>
            <atr>00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F</atr>
        </atrs>
        <isd>A0 00 00 00 03 00 00 00</isd>
        <scp>02_04</scp>
        <tp>T=1</tp>
        <keys>
            <key>
                <type>DES_ECB</type>
                <version>255</version>
                <id>1</id>
                <value>40 41 42 43 44 45 46 47 48 49 4A 4B 4C 4D 4E 4F 40 41 42 43 44 45 46 47</value>
            </key>
        </keys>
    </card>

    <card>
        <name>CardTest02_05</name>
        <implementation>fr.xlim.ssd.opal.library.commands.GP2xCommands</implementation>
        <atrs>
            <atr>00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F</atr>
        </atrs>
        <isd>A0 00 00 00 03 00 00 00</isd>
        <scp>02_05</scp>
        <tp>T=1</tp>
        <keys>
            <key>
                <type>DES_ECB</type>
                <version>255</version>
                <id>1</id>
                <value>40 41 42 43 44 45 46 47 48 49 4A 4B 4C 4D 4E 4F 40 41 42 43 44 45 46 47</value>
            </key>
            <key>
                <type>DES_ECB</type>
                <version>255</version>
                <id>2</id>
                <value>40 41 42 43 44 45 46 47 48 49 4A 4B 4C 4D 4E 4F 40 41 42 43 44 45 46 47</value>
            </key>
            <key>
                <type>DES_ECB</type>
                <version>255</version>
                <id>3</id>
                <value>40 41 42 43 44 45 46 47 48 49 4A 4B 4C 4D 4E 4F 40 41 42 43 44 45 46 47</value>
            </key>
        </keys>
    </card>

    <card>
        <name>CardTest02_14</name>
        <implementation>fr.xlim.ssd.opal.library.commands.GP2xCommands</implementation>
        <atrs>
            <atr>00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F</atr>
        </atrs>
        <isd>A0 00 00 00 03 00 00 00</isd>
        <scp>02_14</scp>
        <tp>T=1</tp>
        <keys>
            <key>
                <type>DES_ECB</type>
                <version>255</version>
                <id>1</id>
                <value>40 41 42 43 44 45 46 47 48 49 4A 4B 4C 4D 4E 4F 40 41 42 43 44 45 46 47</value>
            </key>
        </keys>
    </card>

    <card>
        <name>CardTest02_0A</name>
        <implementation>fr.xlim.ssd.opal.library.commands.GP2xCommands</implementation>
        <atrs>
            <atr>00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F</atr>
        </atrs>
        <isd>A0 00 00 00 03 00 00 00</isd>
        <scp>02_0A</scp>
        <tp>T=1</tp>
        <keys>
            <key>
                <type>DES_ECB</type>
                <version>255</version>
                <id>1</id>
                <value>40 41 42 43 44 45 46 47 48 49 4A 4B 4C 4D 4E 4F 40 41 42 43 44 45 46 47</value>
            </key>
        </keys>
    </card>

    <card>
        <name>CardTest02_45</name>
        <implementation>fr.xlim.ssd.opal.library.commands.GP2xCommands</implementation>
        <atrs>
            <atr>00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F</atr>
        </atrs>
        <isd>A0 00 00 00 03 00 00 00</isd>
        <scp>02_45</scp>
        <tp>T=1</tp>
        <keys>
            <key>
                <type>DES_ECB</type>
                <version>255</version>
                <id>1</id>
                <value>40 41 42 43 44 45 46 47 48 49 4A 4B 4C 4D 4E 4F 40 41 42 43 44 45 46 47</value>
            </key>
            <key>
                <type>DES_ECB</type>
                <version>255</version>
                <id>2</id>
                <value>40 41 42 43 44 45 46 47 48 49 4A 4B 4C 4D 4E 4F 40 41 42 43 44 45 46 47</value>
            </key>
            <key>
                <type>DES_ECB</type>
                <version>255</version>
                <id>3</id>
                <value>40 41 42 43 44 45 46 47 48 49 4A 4B 4C 4D 4E 4F 40 41 42 43 44 45 46 47</value>
            </key>
        </keys>
    </card>

    <card>
        <name>CardTest02_55</name>
        <implementation>fr.xlim.ssd.opal.library.commands.GP2xCommands</implementation>
        <atrs>
            <atr>00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F</atr>
        </atrs>
        <isd>A0 00 00 00 03 00 00 00</isd>
        <scp>02_55</scp>
        <tp>T=1</tp>
        <keys>
            <key>
                <type>DES_ECB</type>
                <version>255</version>
                <id>1</id>
                <value>40 41 42 43 44 45 46 47 48 49 4A 4B 4C 4D 4E 4F 40 41 42 43 44 45 46 47</value>
            </key>
            <key>
                <type>DES_ECB</type>
                <version>255</version>
                <id>2</id>
                <value>40 41 42 43 44 45 46 47 48 49 4A 4B 4C 4D 4E 4F 40 41 42 43 44 45 46 47</value>
            </key>
            <key>
                <type>DES_ECB</type>
                <version>255</version>
                <id>3</id>
                <value>40 41 42 43 44 45 46 47 48 49 4A 4B 4C 4D 4E 4F 40 41 42 43 44 45 46 47</value>
            </key>
        </keys>
    </card>

    <card>
        <name>CardTest03_60</name>
        <implementation>fr.xlim.ssd.opal.library.commands.GP2xCommands</implementation>
        <atrs>
            <atr>00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F</atr>
        </atrs>
        <isd>A0 00 00 00 03 00 00 00</isd>
        <scp>03_60</scp>
        <tp>T=1</tp>
        <keys>
            <key>
                <type>AES_CBC</type>
                <version>1</version>
                <id>1</id>
                <value>40 41 42 43 44 45 46 47 48 49 4A 4B 4C 4D 4E 4F</value>
            </key>
            <key>
                <type>AES_CBC</type>
                <version>1</version>
                <id>2</id>
                <value>40 41 42 43 44 45 46 47 48 49 4A 4B 4C 4D 4E 4F</value>
            </key>
            <key>
                <type>AES_CBC</type>
                <version>1</version>
                <id>3</id>
                <value>40 41 42 43 44 45 46 47 48 49 4A 4B 4C 4D 4E 4F</value>
            </key>
        </keys>
    </card>

    <card>
        <name>CardTest03_00</name>
        <implementation>fr.xlim.ssd.opal.library.commands.GP2xCommands</implementation>
        <atrs>
            <atr>00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F</atr>
        </atrs>
        <isd>A0 00 00 00 03 00 00 00</isd>
        <scp>03_00</scp>
        <tp>T=1</tp>
        <keys>
            <key>
                <type>AES_CBC</type>
                <version>1</version>
                <id>1</id>
                <value>40 41 42 43 44 45 46 47 48 49 4A 4B 4C 4D 4E 4F</value>
            </key>
            <key>
                <type>AES_CBC</type>
                <version>1</version>
                <id>2</id>
                <value>40 41 42 43 44 45 46 47 48 49 4A 4B 4C 4D 4E 4F</value>
            </key>
            <key>
                <type>AES_CBC</type>
                <version>1</version>
                <id>3</id>
                <value>40 41 42 43 44 45 46 47 48 49 4A 4B 4C 4D 4E 4F</value>
            </key>
        </keys>
    </card>

    <card>
        <name>CardTest03_20</name>
        <implementation>fr.xlim.ssd.opal.library.commands.GP2xCommands</implementation>
        <atrs>
            <atr>00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F</atr>
        </atrs>
        <isd>A0 00 00 00 03 00 00 00</isd>
        <scp>03_20</scp>
        <tp>T=1</tp>
        <keys>
            <key>
                <type>AES_CBC</type>
                <version>1</version>
                <id>1</id>
                <value>40 41 42 43 44 45 46 47 48 49 4A 4B 4C 4D 4E 4F</value>
            </key>
            <key>
                <type>AES_CBC</type>
                <version>1</version>
                <id>2</id>
                <value>40 41 42 43 44 45 46 47 48 49 4A 4B 4C 4D 4E 4F</value>
            </key>
            <key>
                <type>AES_CBC</type>
                <version>1</version>
                <id>3</id>
                <value>40 41 42 43 44 45 46 47 48 49 4A 4B 4C 4D 4E 4F</value>
            </key>
        </keys>
    </card>

</opal:cards>
